services:
  tileserver:
    container_name: protomaps-tileserver
    image: ghcr.io/protomaps/go-pmtiles:${PMTILES_IMAGE_VERSION:-v1.27.2}
    ports:
      - "${TILESERVER_IP:-0.0.0.0}:${TILESERVER_PORT:-8080}:8080"
    volumes:
      - ./data:/data:ro
    command: serve /data --cors=* --bucket=file:///data/
    # https://github.com/protomaps/go-pmtiles/issues/59
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
